export const authentication = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    TOKEN_REFRESH_SUCCESS: 'TOKEN_REFRESH_SUCCESS',
    TOKEN_REFRESH_FAIL: 'TOKEN_REFRESH_FAIL'
}

export const createNote = {
    INITIATE_TIMESTAMP_REQUEST: 'INITIATE_TIMESTAMP_REQUEST',
    FULFILL_TIMESTAMP_REQUEST: 'FULFILL_TIMESTAMP_REQUEST',
    RESET_TIMESTAMP: 'RESET_TIMESTAMP',
    CREATE_MESSAGE: 'CREATE_MESSAGE'
}

export const error = {
    GET_ERRORS: 'GET_ERRORS',
    CLEAR_ERRORS: 'CLEAR_ERRORS'
}

export const globalNotification = {
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR',
}